name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=$GITHUB_REF_NAME \
            --build-arg BUILD_DATE=$(date +%s) \
            -t linuxcrafts/samba-ad-dc:latest \
            -t linuxcrafts/samba-ad-dc:$GITHUB_REF_NAME \
            .
        env:
          GITHUB_REF_NAME: ${{ github.ref }}
      
      - name: Push Docker Image
        run: |
          docker push linuxcrafts/samba-ad-dc:latest
          docker push linuxcrafts/samba-ad-dc:$GITHUB_REF_NAME
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
