#!/bin/bash
# MIT License https://opensource.org/licenses/MIT
# Copyright (c) Harol Hunter <hhuntercu.devops@gmail.com>
# Mantainer: LinuxCrafts <craftslinux@gmail.com>

######################### DEFINITIONS #######################

# Setting ENV variables
DOMAIN_CONFIG_FILE="/samba/etc/smb.conf.d/00-domain.conf"
SAMBA_CONFIG_FILE="/samba/etc/smb.conf"
SAMBA_PID="/run/samba/samba.pid"

DEBUG=${DEBUG:=false}
DNS_DOMAIN=${DNS_DOMAIN:=$(hostname -d)}
DNS_DOMAIN=${DNS_DOMAIN:=$(awk -F" " '/search/  {print $2;exit}' /etc/resolv.conf)}
DNS_DOMAIN=${DNS_DOMAIN:=$(echo ${REALM} | tr a-z A-Z)}
if [[ -z ${DNS_DOMAIN} ]] && [[ -e ${DOMAIN_CONFIG_FILE} ]]; then
    DNS_DOMAIN=${DNS_DOMAIN:=$(awk -F" = " '/realm/ {print tolower($2);exit}' ${DOMAIN_CONFIG_FILE})}
fi
DNS_DOMAIN=${DNS_DOMAIN:="my.company.tld"}
DNS_FORWARDER=${DNS_FORWARDER:=$(awk '/^nameserver/ && !/\ 127\./ {print $2;exit}' /etc/resolv.conf)}
WORKGROUP=${WORKGROUP:=$(echo ${DNS_DOMAIN} | cut -f1 -d. | tr a-z A-Z)}
if [[ -z ${REALM} ]] && [[ -e ${DOMAIN_CONFIG_FILE} ]]; then
    REALM=${REALM:=$(awk -F" = " '/realm/ {print toupper($2);exit}' ${DOMAIN_CONFIG_FILE})}
fi
REALM=${REALM:=$(echo ${DNS_DOMAIN} | tr a-z A-Z)}
NETBIOS_NAME=${NETBIOS_NAME:=$(echo ${HOSTNAME} | tr a-z A-Z)}
DNS_BACKEND=${DNS_BACKEND:="SAMBA_INTERNAL"}
FUNCTION_LEVEL=${FUNCTION_LEVEL:="2008_R2"}
ROLE=${ROLE:="dc"}
BACKEND_STORE=${BACKEND_STORE:="tdb"}
ENABLE_ROAMING_PROFILES=${ENABLE_ROAMING_PROFILES:=false}
DISABLE_ISATAP=${DISABLE_ISATAP:=true}
DISABLE_WPAD=${DISABLE_WPAD:=true}
ADMIN_PASSWORD=${ADMIN_PASSWORD:="Admin*123"}
DNS_REVERSE_ZONE=${DNS_REVERSE_ZONE:=$(hostname -i | awk -F. '{print $3"."$2"."$1".in-addr.arpa"}')}

if [[ ${DEBUG} == true ]]; then
    set -x
    LOGGING_CMD="> /dev/null 2>&1"
    DEBUG_LEVEL=${DEBUG_LEVEL:="-d4"}
else
    LOGGING_CMD="> /samba/install.log"
    DEBUG_LEVEL=${DEBUG_LEVEL:="-d0"}
fi

function print_status () {
        if [[ $1 -eq 0 ]]; then 
            echo -e "\b\b\b\b\b\b\e[32m[SUCCESS]\e[0m"
        else
            echo -e "\a\b\b\b\b\b\b\e[31m[FAILED]\e[0m"
        fi     
}

function test_resolv_conf () {
    if [[ $(egrep -c "127.0.0.1|^search" /etc/resolv.conf ) -ge 2 ]]; then
        return 0
    else
        return 1
    fi
}

function test_smb_conf () {
    if [[ ! -e "${DOMAIN_CONFIG_FILE}" ]]; then
        return 1
    fi && \
    testparm -s $SAMBA_CONFIG_FILE > /dev/null 2>&1
    return $?
}

function test_provision () {
       if [[ -e /samba/private/secrets.tdb ]] && \
            [[ -e /samba/private/secrets.keytab ]]; then
        return 0
    else
        return 1
    fi
}

function test_admx_templates () {
    if [[ -d "/samba/state/sysvol/${DNS_DOMAIN}/Policies/PolicyDefinitions" ]] && \
        [[ $(find /samba/state/sysvol/${DNS_DOMAIN}/Policies/ \
        -name PolicyDefinitions -prune -type d -empty| wc -l) -eq 0 ]]; then
        return 0
    else
        return 1
    fi
}

function test_ads_shares () {
    if [[ ! $(net rpc share list -s /samba/etc/smb.conf -U%|  grep -cE "sysvol|netlogon|IPC") -ge 3 ]]; then
        return 1
    fi && \
    
    echo ${ADMIN_PASSWORD} | smbclient //${HOSTNMAE}/sysvol \
        -U administrator -s ${SAMBA_CONFIG_FILE} -c "ls" > /dev/null 2>&1 && \
    echo ${ADMIN_PASSWORD} | smbclient //${HOSTNMAE}/sysvol \
        -U administrator -s ${SAMBA_CONFIG_FILE} -c "ls" > /dev/null 2>&1
    return $?        
}


function test_dns () {
    if [[ $(netstat -ptunl| grep -c 53) -gt 0 ]]; then
        return 0
    else
        return 1
    fi
}

function test_reverse_zone () {

    REVERSE_ZONES_COUNT=$(echo "${ADMIN_PASSWORD}" | samba-tool dns zonelist \
        --reverse -U administrator 127.0.0.1  | head -n1 | cut -f5 -d" ") > /dev/null 2>&1
    if [[ $? -ne 0 ]] || [[ ${REVERSE_ZONES_COUNT} == "0" ]]; then
        return 1
    else
        return 0
    fi
        
    #nslookup -type=soa $DNS_REVERSE_ZONE 127.0.0.1 > /dev/null 2>&1
    return $?
}

function start () {
    if [ -f "/run/samba/samba.pid" ]; then
        kill $(cat /run/samba/samba.pid) > /dev/null 2>&1
        rm -f /run/samba/*.pid
    fi
    if [[ ${DEBUG} == true ]]; then
        echo -e "\033[1;33mStarting samba daemon in foreground... \e[0m"
        exec samba -D -s $SAMBA_CONFIG_FILE ${DEBUG_LEVEL} --debug-stdout
    else
        echo -e "\033[1;33mStarting samba daemon interactivly... \e[0m"
        exec samba -i -s $SAMBA_CONFIG_FILE ${DEBUG_LEVEL} --debug-stdout
    fi
}

function stop () {
    echo -en "Stopping samba daemon ...\t\t\t\t\033[1;33m[WAIT]"
    status=0
    if [ -f "$SAMBA_PID" ]; then
        kill $(cat $SAMBA_PID)
        status=$?
    fi
    print_status $status
    
}

function wait_for_samba_dns () {
    ATTEMPTS=0
    MAX_ATTEMPTS=15
    if [[ ${DNS_BACKEND} == "SAMBA_INTERNAL" ]]; then
        while [[ "$ATTEMPTS" -lt "$MAX_ATTEMPTS" ]] && [[ "$(pgrep -a dns | wc -l)" -eq 0 ]] ; do
            sleep 3s
            ATTEMPTS=$((ATTEMPTS+1))
        done
    fi  && \
    if [[ $MAX_ATTEMPTS -eq 15 ]] && [[ "$(pgrep dns | wc -l)" -eq 0 ]]; then
        return 1
    fi
    return $?
}

function test () {
    echo -en "Checking resolv.conf ... \t\t\t\033[1;33m[WAIT]"
    test_resolv_conf 
    print_status $?

    echo -en "Checking smb.conf ... \t\t\t\t\033[1;33m[WAIT]"
    test_smb_conf
    print_status $?    

    echo -en "Checking Samba provision ... \t\t\t\033[1;33m[WAIT]"
    test_provision
    print_status $?

    echo -en "Checking krb5.conf ... \t\t\t\t\033[1;33m[WAIT]"
    cmp -s /etc/krb5.conf /samba/private/krb5.conf > /dev/null 2>&1
    print_status $?

    echo -en "Checking local AD database ... \t\t\t\033[1;33m[WAIT]"
    samba-tool dbcheck -qs /samba/etc/smb.conf > /dev/null 2>&1
    print_status $?

    echo -en "Checking ADMX Templates ...\t\t\t\033[1;33m[WAIT]"
    test_admx_templates
    print_status $?

    # Samba needs to be running
    echo -en "Starting Samba ...\t\t\t\t\033[1;33m[WAIT]"
    samba -D -s $SAMBA_CONFIG_FILE && \
    wait_for_samba_dns
    print_status $?

    echo -en "Checking ADS shares ... \t\t\t\033[1;33m[WAIT]"
    test_ads_shares
    print_status $?

    echo -en "Checking DNS server ...\t\t\t\t\033[1;33m[WAIT]"
    test_dns
    print_status $?

    echo -en "  Checking Reverse DNS resolution ...\t\t\033[1;33m[WAIT]" 
    test_reverse_zone
    print_status $?    

    echo -en "  Checking for ldap SRV RECORD ...\t\t\033[1;33m[WAIT]" 
    nslookup -type=SRV _ldap._tcp.${DNS_DOMAIN} 127.0.0.1 > /dev/null 2>&1
    print_status $?

    echo -en "  Checking for krb5 SRV RECORD ...\t\t\033[1;33m[WAIT]" 
    nslookup -type=SRV _kerberos._udp.${DNS_DOMAIN} 127.0.0.1 > /dev/null 2>&1
    print_status $?

    #KRB5_TRACE=/dev/stdout kinit administrator
}

# Adding localhost and DNS domain to resolv.conf
function generate_resolv_conf () {
    echo "search ${DNS_DOMAIN}" > /etc/resolv.conf && \
    echo "nameserver 127.0.0.1" >> /etc/resolv.conf 
    return $?
}

# Filling smb.conf
function write_smb_conf() { 
    rm -f /etc/samba/smb.conf && \
    
    echo "workgroup = ${WORKGROUP}" > $DOMAIN_CONFIG_FILE && \
    echo "realm = ${REALM}" >> $DOMAIN_CONFIG_FILE && \
    echo "netbios name = ${NETBIOS_NAME}" >> $DOMAIN_CONFIG_FILE && \

    if [[ "${DNS_FORWARDER}" != "127.0.0.1" ]]; then
        echo "dns forwarder = ${DNS_FORWARDER}" >> $DOMAIN_CONFIG_FILE
    fi && \
    
    # Enable user profiles shares in server
    if [[ $ENABLE_ROAMING_PROFILES == true ]]; then
        mkdir -p -m 2750 /users/
        chmod 2750 /users/
        mv /samba/etc/smb.conf.d/93-users-profiles.conf.orig /samba/etc/smb.conf.d/93-users-profiles.conf
    fi && \

    rm -f /samba/etc/smb.conf.d/includes && \
    for custom_conf in $(ls -1 /samba/etc/smb.conf.d/*.conf); do 
        echo "include = $custom_conf" >> /samba/etc/smb.conf.d/includes
    done 

    echo "    path = /samba/state/sysvol/${DNS_DOMAIN}/scripts" >>  /samba/etc/smb.conf.d/90-ads-shares.conf
    
    return $?
}

# Provisioning Samba4 AD DC
function provision_domain() {
    samba-tool domain provision -q ${DEBUG_LEVEL} \
        --domain=${WORKGROUP} \
        --host-name=${NETBIOS_NAME} \
        --host-ip=$(hostname -i) \
        --adminpass=${ADMIN_PASSWORD} \
        --dns-backend=${DNS_BACKEND} \
        --server-role=${ROLE} \
        --function-level=${FUNCTION_LEVEL} \
        --use-rfc2307 \
        --backend-store=${BACKEND_STORE} \
        --targetdir="/samba" \
        --realm=${REALM} \
        --configfile=${SAMBA_CONFIG_FILE} > /dev/null 2>&1 && \
        cp /samba/private/krb5.conf /etc/krb5.conf
    return $?
}

# Provisiong DNS
    function setting_dns() {
    echo "${ADMIN_PASSWORD}" | samba-tool dns zonecreate ${DEBUG_LEVEL} \
        -s ${SAMBA_CONFIG_FILE} \
        -P -U administrator \
        ${HOSTNAME}.${DNS_DOMAIN} ${DNS_REVERSE_ZONE} > /dev/null 2>&1 && \

    echo "${ADMIN_PASSWORD}" | samba-tool dns add ${DEBUG_LEVEL} \
        -s ${SAMBA_CONFIG_FILE} \
        -P -U administrator \
        ${HOSTNAME}.${DNS_DOMAIN} ${DNS_REVERSE_ZONE} \
        $(hostname -i | awk -F. '{print $4}') PTR \
        ${HOSTNAME}.${DNS_DOMAIN} > /dev/null 2>&1 && \

    echo "${ADMIN_PASSWORD}" | samba-tool dns add ${DEBUG_LEVEL} \
        -s ${SAMBA_CONFIG_FILE} \
        -P -U administrator \
        ${HOSTNAME}.${DNS_DOMAIN} ${DNS_DOMAIN} \
         _kerberos-master._udp SRV \
         "${HOSTNAME}.${DNS_DOMAIN} 88 0 100" > /dev/null 2>&1 && \

    echo "${ADMIN_PASSWORD}" | samba-tool dns add ${DEBUG_LEVEL} \
        -s ${SAMBA_CONFIG_FILE} \
        -P -U administrator \
        ${HOSTNAME}.${DNS_DOMAIN} ${DNS_DOMAIN} \
         _kerberos-master._tcp SRV \
         "${HOSTNAME}.${DNS_DOMAIN} 88 0 100" > /dev/null 2>&1 && \

    # Disabling WPAD and ISATAP DNS records for security reasons
    if [[ $DISABLE_WPAD == true ]]; then
        echo "${ADMIN_PASSWORD}" | samba-tool dns add  ${DEBUG_LEVEL} \
            ${HOSTNAME} ${DNS_DOMAIN} wpad A 127.0.0.1 -P \
            -U administrator > /dev/null 2>&1
    fi && \
    if [[ $DISABLE_ISATAP == true ]]; then
        echo "${ADMIN_PASSWORD}" | samba-tool dns add ${DEBUG_LEVEL} \
            ${HOSTNAME} ${DNS_DOMAIN} isatap A 127.0.0.1 -P \
            -U administrator > /dev/null 2>&1
    fi
    return $?
}

# Installing GPO ADMX Templates
function install_admx_templates () {
    target_dir="/samba/state/sysvol/${DNS_DOMAIN}/Policies/PolicyDefinitions"
    tar -xJf /tmp/admx.xz -C /tmp
    # cp -R /tmp/admx $target_dir && \
    # chown -R 3000000:users $target_dir && \
    # chmod -R 750 $target_dir && \
    echo "${ADMIN_PASSWORD}" | samba-tool gpo admxload -s ${SAMBA_CONFIG_FILE} ${DEBUG_LEVEL} --admx-dir=/tmp/admx \
      -s /samba/etc/smb.conf \
      -U administrator > /dev/null 2>&1 && \
    rm -rf /tmp/admx*
    return $?
}

function setup () {
    # Adding localhost to resolv.conf 
    test_resolv_conf
    if [[ $? -ne 0 ]]; then
        echo -en "Regenerating resolv.conf ...\t\t\t\t\033[1;33m[WAIT]"
        generate_resolv_conf
        print_status $?
    fi

    # Write local info to smb.conf
    if [[ ! -s $DOMAIN_CONFIG_FILE ]]; then
        echo -en "Writing samba settings ...\t\t\t\t\033[1;33m[WAIT]"
        write_smb_conf
        print_status $?
    fi

    # Provision samba domain
    test_provision
    if [[ $? -ne 0 ]]; then
        echo -en "Provisioning Samba Domain ...\t\t\t\t\033[1;33m[WAIT]"
        provision_domain 
        print_status $?
    fi

    # Copying krb5.conf
    echo -en "Copying krb5.conf to default location ...\t\t\t\t\033[1;33m[WAIT]"
    if [[ -e /samba/private/krb5.conf ]]; then
        cp /samba/private/krb5.conf /etc/krb5.conf
    fi
    print_status $?

    # Samba needs to be running
    echo -en "Starting samba ...\t\t\t\t\t\t\t\033[1;33m[WAIT]"
    samba -D -s $SAMBA_CONFIG_FILE && \
    # Waiting for Samba DNS daemon to start 
    wait_for_samba_dns
    print_status $?

    # Install ADMX Templates
    test_admx_templates
    if [[ $? -ne 0 ]]; then
        echo -en "Installing ADMX Templates ...\t\t\t\t\t\t\033[1;33m[WAIT]"
        #install_admx_templates
        print_status $?
    fi

    # Provision DNS reverse zone
    test_reverse_zone
    if [[ $? -ne 0 ]]; then
        echo -en "Provisioning DNS ... \t\t\t\t\033[1;33m[WAIT]"
        setting_dns 
        print_status $?
    fi
}



##################################################################################

generate_resolv_conf

if [[ -e /samba/private/krb5.conf ]]; then
    cp /samba/private/krb5.conf /etc/krb5.conf
fi

if [[ $# -eq 0 ]]; then
    setup
    start 
else
    if [[ $1 == "-" ]]; then
        shift
    fi

    case "$1" in
        setup)
            setup
            shift
            exec "$@"            
        ;;
        start)
            setup
            start
        ;;
        test)
            test 
            shift
            exec "$@"
        ;;   
    esac

fi
exit 0