# Active Directory shares definitions
[sysvol]
    path = /samba/state/sysvol
    comment = Logon server share
    read only = no
    browsable = yes
    guest ok = no
    create mask = 0755
    directory mask = 0755  

[netlogon]
    comment = Logon server share
    read only = yes
    browsable = yes
    guest ok = no
    create mask = 0755
    directory mask = 0755
