name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'          # Match tags starting with 'v'
    branches:
      - master      
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: registry-1.docker.io/linuxcrafts
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=$GITHUB_REF_NAME \
            --build-arg BUILD_DATE=$(date +%s) \
            -t linuxcrafts/samba-ad-dc:latest \
            --push \
            .
            docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=$GITHUB_REF_NAME \
            --build-arg BUILD_DATE=$(date +%s) \
            -t linuxcrafts/samba-ad-dc:$GITHUB_REF_NAME \
            --push \
            .            
        env:
          GITHUB_REF_NAME: ${{ github.ref }}
      
      - name: Push Docker Image
        run: |
          docker push linuxcrafts/samba-ad-dc:latest -u $DOCKER_USERNAME -
          docker push linuxcrafts/samba-ad-dc:$GITHUB_REF_NAME
          - name: login to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
